---

- hosts: kibana
  remote_user: vagrant
  become: yes
  vars:
    kibana_on_baremetal: false
    kibana_on_docker: true
    kibana_on_kubernetes: false
    kibana_elasticsearch_url: <CONFIGURE_IT>
  roles:
    - kibana
