---

dependencies:

  - role: kibana/baremetal
    when: kibana_install_type == "baremetal"

  - role: kibana/docker
    when: kibana_install_type == "docker"

  - role: kibana/kubernetes
    when: kibana_install_type == "kubernetes"
