---

- name: KIBANA DEBIAN | Set OSS variables
  set_fact:
    kibana_package_name: "{{ kibana_oss_package_name }}"
    kibana_apt_url: "{{ kibana_oss_apt_url }}"
  when: kibana_oss_version

- name: KIBANA DEBIAN | Import key
  apt_key:
    url: "{{ kibana_apt_key }}"
    state: present

- name: KIBANA DEBIAN | Add repository
  apt_repository:
    repo: "{{ kibana_apt_url }}"
    state: present

- name: KIBANA DEBIAN | Install packages
  package:
    name: "{{ kibana_package_name }}"
    update_cache: yes
    state: present
