---

- name: KIBANA | Import environment variables
  include_vars: "{{ ansible_os_family | lower }}.yml"

- name: KIBANA | Manage environment tasks
  include_tasks: "{{ ansible_os_family | lower }}.yml"

- name: KIBANA | Configuration
  import_tasks: configure.yml
