---

- name: KIBANA | Manage Debian environment
  import_tasks: debian.yml
  when: ansible_os_family == 'Debian' or ansible_os_family == 'Ubuntu'

- name: KIBANA | Manage Redhat environment
  import_tasks: redhat.yml
  when: ansible_os_family == 'RedHat' or ansible_os_family == 'CentOS'

- name: KIBANA | Configuration
  import_tasks: configure.yml
