---

###
# DEBIAN
###

# Package name
kibana_package_name: kibana={{ kibana_version }}*
kibana_oss_package_name: kibana-oss={{ kibana_version }}*

# DEB URL
kibana_apt_key: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
kibana_apt_url: "deb https://artifacts.elastic.co/packages/{{ kibana_major_version }}/apt stable main"
kibana_oss_apt_url: "deb https://artifacts.elastic.co/packages/oss-{{ kibana_major_version }}/apt stable main"
